### ISSUE TITLE
Authorization找不到

### ISSUE THREAD

**Issue by ghost** [Cl0udG0d/Fofa-python-#2]
Authorization的api.fofa.so没有看到发起请求啊，是在哪里呀

**Comment by Cl0udG0d** [comment]
能找到的，多点翻页，F12进行检查
![image](https://user-images.githubusercontent.com/45556496/121926707-d21bca80-cd70-11eb-8a22-ae6c0dce79c1.png)
（除非FOFA又更新了，不过我感觉不太可能更新这么频繁
