### ISSUE TITLE
当总页数小于5的时候会报错

### ISSUE THREAD

**Issue by yq1ng** [Cl0udG0d/Fofa-python-#5]
爬取总页数小于5的时候会报错：`IndexError: list index out of range`  
建议修改 `fofa.py` 第 17 行 为 `pagenum=tree.xpath('//li[@class="number"]/text()')[-1]`

**Comment by Cl0udG0d** [comment]
啊哈，刚才尝试了一下，确实存在这样的问题，感谢建议，已修改 :)
不过经过测试还是存在一个新的问题，例如搜索：
> "联创互联jdkslajlkdasdkja"

一个肯定不存在的值，即便使用`pagenum=tree.xpath('//li[@class="number"]/text()')[-1]`同样会报错
![image](https://user-images.githubusercontent.com/45556496/131158035-3d4659f6-f804-42f9-9254-b730270cfe52.png)

**Comment by yq1ng** [comment]
这个问题加一个 `try except` 即可解决  
```
    try:
        pagenum=tree.xpath('//li[@class="number"]/text()')[-1]
    except Exception as e:
        pagenum = '0'
```

**Comment by Cl0udG0d** [comment]
我觉得很棒

**Comment by Cl0udG0d** [comment]
为了防止出错卡退,我修改上述代码为了
```python
    try:
        pagenum = tree.xpath('//li[@class="number"]/text()')[-1]
    except Exception as e:
        print(e)
        pagenum = '0'
        pass
```
 感谢指出错误与分享
