### ISSUE TITLE
现在还能使用嘛？

### ISSUE THREAD

**Issue by sunu11** [Cl0udG0d/Fofa-python-#6]
测试了一下，无法下载～～

**Comment by Cl0udG0d** [comment]
当然是可以的，注意看readme里面的内容，config文件里面现在配置的是cookie，不是Authorization

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。

**Comment by sunu11** [comment]
收到，老哥，我ok了，你这段话歧义了2333:2021-4-4 对最新版fofa更新做出对应更新，注意：config.py文件中不再是以cookie来进行保证登录，而是使用Authorization，Authorization的值可以登录后F12在https://api.fofa.so/v1/search网址请求头中看到
