### ISSUE TITLE
师傅，现在已经获取不到了

### ISSUE THREAD

**Issue by lpy30m** [Cl0udG0d/Fofa-python-#8]

**Comment by Cl0udG0d** [comment]
刚才测试了一下会员账号是能够正常使用的，我猜测你使用的账号是非会员，所以使用的错误现象是获取了第六页之后的内容为空？

如果没有会员账号，欢迎使用该项目的姊妹项目：https://github.com/Cl0udG0d/Fofa-hack

如果你使用的是会员账号，那可能是因为cookie复制错误而导致的，欢迎查看该ISSUE
+ https://github.com/Cl0udG0d/Fofa-script/issues/6

**Comment by lpy30m** [comment]
好的谢谢师傅回答

**Comment by Cl0udG0d** [comment]
无妨，有啥问题欢迎加我微信沟通
